### ISSUE TITLE
[Feature request] Arbitrary URL wrapper

### ISSUE THREAD

**Issue by parkerlreed** [BrowserSync/browsersync.github.io#14]
What I've been trying to do is have two machines load the same webpage (Google, YouTube, Reddit) and have the scrolls and clicks mirrored across the machines.

I've tried to load them in an iframe but still doesn't work. 

My idea was, if it's possible, was to have a URL bar in the management console (3001 by default) where you could tell all the connected browsers to load.

**Comment by shinnn** [comment]
Please open a feature request ticket in https://github.com/BrowserSync/browser-sync/issues. Here is just a site repo.
