### ISSUE TITLE
Embedded CSS ?

### ISSUE THREAD

**Issue by SheepDomination** [BrowserSync/browsersync.github.io#20]
Can I still use BrowserSync if my CSS is embedded or must the CSS files be external ?

**Comment by shinnn** [comment]
Yes :+1: 

When you edit the watched HTML that has inline CSS, Broswersync reloads the browser.

**Comment by SheepDomination** [comment]
BrowserSync.io doesn't actually include browsers, correct, it can load browsers externally, if I understand correctly ?

**Comment by shinnn** [comment]
[browsersync.io](http://www.browsersync.io/) is the website of Browsersync. Do you mean Browsersync?

**Comment by SheepDomination** [comment]
Yes, I mean BrowserSync :)

**Comment by shinnn** [comment]
> BrowserSync doesn't actually include browsers

Yes, Browsersync uses the browser you've installed to your PC.

**Comment by SheepDomination** [comment]
I thought it loads them externally online :-(

**Comment by shinnn** [comment]
And, please report Brosersync-related issue to https://github.com/BrowserSync/browser-sync. Here is just a repository of Browsersync website.

**Comment by SheepDomination** [comment]
The concept is good, but I don't know where to get all mobile and desktop browsers to preview on my desktop :(

**Comment by shinnn** [comment]
@SheepDomination, https://github.com/BrowserSync/browsersync.github.io/issues/20#issuecomment-110004763

> please report Brosersync-related issue to https://github.com/BrowserSync/browser-sync. Here is just a repository of Browsersync website.

**Comment by shinnn** [comment]
And please read [the contribution guide](https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report) before opening new issues.
