### ISSUE TITLE
Updating _doc/*.json generates noisy diff

### ISSUE THREAD

**Issue by shinnn** [BrowserSync/browsersync.github.io#23]
Like https://github.com/BrowserSync/browsersync.github.io/commit/881ca71ff4b4344767b1b90c49e5b25521adb204#diff-f63bc924b61374f1fda1e1caa1070f49

When I build this site all the `file` properties will be updated, because my machine doesn't have `/Users/shakyshane` directory (of course).

@shakyShane Should `_doc/*.json` be included in the repository? Or can we add them to `.gitignore`?

**Comment by shakyShane** [comment]
Yeah I think it'd be fine to ignore those files.
