### ISSUE TITLE
sudo install -g

### ISSUE THREAD

**Issue by gbell12** [BrowserSync/browsersync.github.io#26]
In your docs, you guys recommend against using sudo for a -g install.  The site you point to recommends chowning /usr to the current user (or /usr/local)!  From a security standpoint, this is an extremely bad idea - it lets anything the current user runs modify binaries and libraries for the entire system.

Even if I just chown /usr/lib/node_modules, that's still not a great idea.

Secondly, if I install browser-sync locally (no -g), there's no 'bin' directory under ~/node_modules/browser-sync, nor does it put its binary in ~/node_modules/.bin.  I'm not an npm expert, but if I look at how bower installs itself, there's ~/node_modules/.bin/bower.

 Maybe support for local installs is still in the making?

**Comment by shinnn** [comment]
> The site you point to recommends chowning /usr to the current user (or /usr/local)! From a security standpoint, this is an extremely bad idea 

Discussion related to this problem goes to https://github.com/npm/npm/issues.

> there's no 'bin' directory under ~/node_modules/browser-sync, nor does it put its binary in ~/node_modules/.bin.

```
$ npm i browser-sync
$ ls node_modules/browser-sync/bin node_modules/.bin/browser-sync
node_modules/.bin/browser-sync

node_modules/browser-sync/bin:
browser-sync.js
```

**Comment by shakyShane** [comment]
@gbell12 as @shinnn points out, you can certainly run Browsersync locally.

**Comment by gbell12** [comment]
Thanks @shakyShane, but as I said, the installer didn't put anything in ~/node_modules/.bin.  Oddly, a subsequent install did.  No idea why.
@shinnn sure, it's npm's documentation but you guys are propagating the idea by linking to it.

Whatever.  Thanks for the great software.  It's almost startling when it does its thing!  And the synced filling of forms was quite a bonus.
