### ISSUE TITLE
Installation instructions fail in Debian Jessie

### ISSUE THREAD

**Issue by sampablokuper** [BrowserSync/browsersync.github.io#29]
The installation instructions at http://www.browsersync.io say:

> Get started in 5 minutes.
> 
> 1. Install Node.js
>
> Browsersync is a module for Node.js, a platform for fast network applications. There are convenient > [installers for MacOS, Windows and Linux](http://nodejs.org/download/).

OK. I followed the link, which linked in turn to [this page](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions) for installation on Debian, which says, "**A Node.js package is also available in the official repo for Debian Sid (unstable), Jessie (testing) and Wheezy (wheezy-backports) as "nodejs".**"

Great. `# apt-get install nodejs` reported no errors.

Your installation instructions continue:

> 2. Install Browsersync
>
> The Node.js package manager (npm) is used to install Browsersync from [a repository](https://npmjs.org/package/browser-sync). Open a terminal window and run the following command:
>
> npm install -g browser-sync

That didn't work:

    $ npm install -g browser-sync
    bash: npm: command not found

Hm, that's a bug in your instructions. OK, maybe there's a workaround? I tried `# apt-get install npm`, which reported no errors.

Now, though, when I run your suggested install command, I get this output:

    $ npm install -g browser-sync
    npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules'
    npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules']
    npm ERR!   errno: 3,
    npm ERR!   code: 'EACCES',
    npm ERR!   path: '/usr/local/lib/node_modules',
    npm ERR!   fstream_type: 'Directory',
    npm ERR!   fstream_path: '/usr/local/lib/node_modules/browser-sync',
    npm ERR!   fstream_class: 'DirWriter',
    npm ERR!   fstream_stack: 
    npm ERR!    [ '/usr/lib/nodejs/fstream/lib/writer.js:171:23',
    npm ERR!      '/usr/lib/nodejs/mkdirp/index.js:46:53',
    npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.

    npm ERR! System Linux 3.16.0-4-686-pae
    npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "browser-sync"
    npm ERR! cwd /home/sampablokuper
    npm ERR! node -v v0.10.29
    npm ERR! npm -v 1.4.21
    npm ERR! path /usr/local/lib/node_modules
    npm ERR! fstream_path /usr/local/lib/node_modules/browser-sync
    npm ERR! fstream_type Directory
    npm ERR! fstream_class DirWriter
    npm ERR! code EACCES
    npm ERR! errno 3
    npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules'
    npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
    npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:46:53
    npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/sampablokuper/npm-debug.log
    npm ERR! not ok code 0

Running `npm install -g` as root/sudo seems like bad advice, so I'm not going to do that just yet. That leaves me without a working installation of BrowserSync, so the installation instructions have proven inadequate to get a Debian Jessie user to the point of having a working BrowserSync install.

(Also, this took more than 5 minutes.)

Hope a resolution for this can be found, as I'd love to try BrowserSync!

**Comment by shinnn** [comment]
https://github.com/npm/npm/issues/8058#issuecomment-95821549

**Comment by sampablokuper** [comment]
Thanks for the pointer, but I'm afraid it doesn't fix the *documentation bug* that I reported above.

If you require your users to install some particular version of `npm`, and especially if you require them to do so in some non-obvious way (e.g. not via `apt-get install npm`) then you should specify this in your documentation.

Until then, please consider this bug ***open***.

**Comment by sampablokuper** [comment]
Also, as I've just discovered, upgrading to npm@2 doesn't resolve the issue.

From scratch:

    # apt-get install nodejs
    # apt-get install nodejs-legacy # Prevents namespace conflict w/"Node" packet radio package.
    # 'curl https://npmjs.org/install.sh | sh' # <rant>Security heebie-jeebies.</rant>
    # exit
    $ npm -v
    2.14.0
    $ npm install -g browser-sync
    npm ERR! tar.unpack untar error /home/sampablokuper/.npm/browser-sync/2.8.2/package.tgz
    npm ERR! Linux 3.16.0-4-686-pae
    npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "browser-sync"
    npm ERR! node v0.10.29
    npm ERR! npm  v2.14.0
    npm ERR! path /usr/lib/node_modules/browser-sync
    npm ERR! code EACCES
    npm ERR! errno 3

    npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/browser-sync'
    npm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/browser-sync']
    npm ERR!   errno: 3,
    npm ERR!   code: 'EACCES',
    npm ERR!   path: '/usr/lib/node_modules/browser-sync',
    npm ERR!   fstream_type: 'Directory',
    npm ERR!   fstream_path: '/usr/lib/node_modules/browser-sync',
    npm ERR!   fstream_class: 'DirWriter',
    npm ERR!   fstream_stack: 
    npm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
    npm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
    npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/sampablokuper/npm-debug.log

**Comment by sampablokuper** [comment]
Here's the contents of `/home/sampablokuper/npm-debug.log`:

    0 info it worked if it ends with ok
    1 verbose cli [ 'node', '/usr/bin/npm', 'install', '-g', 'browser-sync' ]
    2 info using npm@2.14.0
    3 info using node@v0.10.29
    4 verbose node symlink /usr/bin/node
    5 verbose install initial load of /usr/lib/package.json
    6 verbose readDependencies loading dependencies from /usr/lib/package.json
    7 silly cache add args [ 'browser-sync', null ]
    8 verbose cache add spec browser-sync
    9 silly cache add parsed spec { raw: 'browser-sync',
    9 silly cache add   scope: null,
    9 silly cache add   name: 'browser-sync',
    9 silly cache add   rawSpec: '',
    9 silly cache add   spec: '*',
    9 silly cache add   type: 'range' }
    10 silly addNamed browser-sync@*
    11 verbose addNamed "*" is a valid semver range for browser-sync
    12 silly addNameRange { name: 'browser-sync', range: '*', hasData: false }
    13 silly mapToRegistry name browser-sync
    14 silly mapToRegistry using default registry
    15 silly mapToRegistry registry https://registry.npmjs.org/
    16 silly mapToRegistry uri https://registry.npmjs.org/browser-sync
    17 verbose addNameRange registry:https://registry.npmjs.org/browser-sync not in flight; fetching
    18 verbose request uri https://registry.npmjs.org/browser-sync
    19 verbose request no auth needed
    20 info attempt registry request try #1 at 11:55:04
    21 verbose request id e2f4639462d59047
    22 http request GET https://registry.npmjs.org/browser-sync
    23 http 200 https://registry.npmjs.org/browser-sync
    24 silly get cb [ 200,
    24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
    24 silly get     etag: '"3MHMQ79ZBBYAO426ASLRHLTJI"',
    24 silly get     'content-type': 'application/json',
    24 silly get     'cache-control': 'max-age=60',
    24 silly get     'content-length': '373853',
    24 silly get     'accept-ranges': 'bytes',
    24 silly get     date: 'Tue, 25 Aug 2015 10:54:26 GMT',
    24 silly get     via: '1.1 varnish',
    24 silly get     age: '15',
    24 silly get     connection: 'keep-alive',
    24 silly get     'x-served-by': 'cache-lcy1130-LCY',
    24 silly get     'x-cache': 'HIT',
    24 silly get     'x-cache-hits': '1',
    24 silly get     'x-timer': 'S1440500066.906048,VS0,VE2',
    24 silly get     vary: 'Accept' } ]
    25 verbose get saving browser-sync to /home/sampablokuper/.npm/registry.npmjs.org/browser-sync/.cache.json
    26 verbose makeDirectory /home/sampablokuper/.npm creation not in flight; initializing
    27 silly makeDirectory /home/sampablokuper/.npm uid: 1000 gid: 1000
    28 silly addNameRange number 2 { name: 'browser-sync', range: '*', hasData: true }
    29 silly addNameRange versions [ 'browser-sync',
    29 silly addNameRange   [ '0.1.0',
    29 silly addNameRange     '0.1.1',
    29 silly addNameRange     '0.1.3',
    29 silly addNameRange     '0.1.5',
    29 silly addNameRange     '0.1.6',
    29 silly addNameRange     '0.1.7',
    29 silly addNameRange     '0.1.8',
    29 silly addNameRange     '0.1.9',
    29 silly addNameRange     '0.1.10',
    29 silly addNameRange     '0.2.0',
    29 silly addNameRange     '0.2.1',
    29 silly addNameRange     '0.3.0',
    29 silly addNameRange     '0.3.1',
    29 silly addNameRange     '0.3.2',
    29 silly addNameRange     '0.3.3',
    29 silly addNameRange     '0.3.4',
    29 silly addNameRange     '0.3.5',
    29 silly addNameRange     '0.3.6',
    29 silly addNameRange     '0.3.7',
    29 silly addNameRange     '0.3.8',
    29 silly addNameRange     '0.3.10',
    29 silly addNameRange     '0.4.0',
    29 silly addNameRange     '0.4.1',
    29 silly addNameRange     '0.4.2',
    29 silly addNameRange     '0.4.21',
    29 silly addNameRange     '0.4.3',
    29 silly addNameRange     '0.4.4',
    29 silly addNameRange     '0.4.5',
    29 silly addNameRange     '0.4.6',
    29 silly addNameRange     '0.4.7',
    29 silly addNameRange     '0.4.8',
    29 silly addNameRange     '0.4.9',
    29 silly addNameRange     '0.4.10',
    29 silly addNameRange     '0.4.11',
    29 silly addNameRange     '0.4.12',
    29 silly addNameRange     '0.5.0',
    29 silly addNameRange     '0.5.1',
    29 silly addNameRange     '0.5.2',
    29 silly addNameRange     '0.5.3',
    29 silly addNameRange     '0.5.4',
    29 silly addNameRange     '0.5.5',
    29 silly addNameRange     '0.5.6',
    29 silly addNameRange     '0.5.7',
    29 silly addNameRange     '0.5.8',
    29 silly addNameRange     '0.5.9',
    29 silly addNameRange     '0.6.0',
    29 silly addNameRange     '0.6.1',
    29 silly addNameRange     '0.6.2',
    29 silly addNameRange     '0.7.0',
    29 silly addNameRange     '0.7.1',
    29 silly addNameRange     '0.7.2',
    29 silly addNameRange     '0.7.3',
    29 silly addNameRange     '0.7.4',
    29 silly addNameRange     '0.7.5',
    29 silly addNameRange     '0.7.7',
    29 silly addNameRange     '0.8.0',
    29 silly addNameRange     '0.8.1',
    29 silly addNameRange     '0.8.2',
    29 silly addNameRange     '0.9.0',
    29 silly addNameRange     '0.9.1',
    29 silly addNameRange     '1.0.0',
    29 silly addNameRange     '1.1.0',
    29 silly addNameRange     '1.1.1',
    29 silly addNameRange     '1.1.2',
    29 silly addNameRange     '1.2.0',
    29 silly addNameRange     '1.2.1',
    29 silly addNameRange     '1.3.0',
    29 silly addNameRange     '1.3.2',
    29 silly addNameRange     '1.3.3',
    29 silly addNameRange     '1.3.4',
    29 silly addNameRange     '1.3.5',
    29 silly addNameRange     '1.3.6',
    29 silly addNameRange     '1.3.7',
    29 silly addNameRange     '1.5.0',
    29 silly addNameRange     '1.5.1',
    29 silly addNameRange     '1.5.2',
    29 silly addNameRange     '1.5.3',
    29 silly addNameRange     '1.5.4',
    29 silly addNameRange     '1.5.5',
    29 silly addNameRange     '1.5.6',
    29 silly addNameRange     '1.5.7',
    29 silly addNameRange     '1.5.8',
    29 silly addNameRange     '1.5.9',
    29 silly addNameRange     '1.6.0',
    29 silly addNameRange     '1.6.1',
    29 silly addNameRange     '1.6.2',
    29 silly addNameRange     '1.6.3',
    29 silly addNameRange     '1.6.4',
    29 silly addNameRange     '1.6.5',
    29 silly addNameRange     '1.7.0',
    29 silly addNameRange     '1.7.1',
    29 silly addNameRange     '1.7.2',
    29 silly addNameRange     '1.7.3',
    29 silly addNameRange     '1.8.0',
    29 silly addNameRange     '1.8.1',
    29 silly addNameRange     '1.8.2',
    29 silly addNameRange     '1.8.3',
    29 silly addNameRange     '1.9.0',
    29 silly addNameRange     '1.9.1',
    29 silly addNameRange     '2.0.0-rc1',
    29 silly addNameRange     '2.0.0-rc2',
    29 silly addNameRange     '2.0.0-rc3',
    29 silly addNameRange     '2.0.0-rc4',
    29 silly addNameRange     '2.0.0-rc5',
    29 silly addNameRange     '2.0.0-rc6',
    29 silly addNameRange     '2.0.0-rc7',
    29 silly addNameRange     '2.0.0-rc8',
    29 silly addNameRange     '2.0.0-rc9',
    29 silly addNameRange     '2.0.0-rc10',
    29 silly addNameRange     '2.0.0',
    29 silly addNameRange     '2.0.1',
    29 silly addNameRange     '2.1.0',
    29 silly addNameRange     '2.1.1',
    29 silly addNameRange     '2.1.2',
    29 silly addNameRange     '2.1.3',
    29 silly addNameRange     '2.1.4',
    29 silly addNameRange     '2.1.6',
    29 silly addNameRange     '2.2.0',
    29 silly addNameRange     '2.2.1',
    29 silly addNameRange     '2.2.2',
    29 silly addNameRange     '2.2.3',
    29 silly addNameRange     '2.2.4',
    29 silly addNameRange     '2.2.5',
    29 silly addNameRange     '2.3.0',
    29 silly addNameRange     '2.3.1',
    29 silly addNameRange     '2.3.2',
    29 silly addNameRange     '2.4.0',
    29 silly addNameRange     '2.4.1',
    29 silly addNameRange     '2.5.0',
    29 silly addNameRange     '2.5.1',
    29 silly addNameRange     '2.5.2',
    29 silly addNameRange     '2.5.3',
    29 silly addNameRange     '2.6.0',
    29 silly addNameRange     '2.6.1',
    29 silly addNameRange     '2.6.2',
    29 silly addNameRange     '2.6.3',
    29 silly addNameRange     '2.6.4',
    29 silly addNameRange     '2.6.5',
    29 silly addNameRange     '2.6.6',
    29 silly addNameRange     '1.9.2',
    29 silly addNameRange     '2.6.7',
    29 silly addNameRange     '2.6.8',
    29 silly addNameRange     '2.6.9',
    29 silly addNameRange     '2.6.10',
    29 silly addNameRange     '2.6.11',
    29 silly addNameRange     '2.7.0',
    29 silly addNameRange     '2.7.1',
    29 silly addNameRange     '2.7.2',
    29 silly addNameRange     '2.7.3',
    29 silly addNameRange     '2.7.4',
    29 silly addNameRange     '2.7.5',
    29 silly addNameRange     '2.7.6',
    29 silly addNameRange     '2.7.7',
    29 silly addNameRange     '2.7.8',
    29 silly addNameRange     '2.7.9',
    29 silly addNameRange     '2.7.10',
    29 silly addNameRange     '2.7.11',
    29 silly addNameRange     '2.7.12',
    29 silly addNameRange     '2.7.13',
    29 silly addNameRange     '2.8.0',
    29 silly addNameRange     '2.8.1',
    29 silly addNameRange     '2.8.2' ] ]
    30 silly addNamed browser-sync@2.8.2
    31 verbose addNamed "2.8.2" is a plain semver version for browser-sync
    32 silly mapToRegistry name browser-sync
    33 silly mapToRegistry using default registry
    34 silly mapToRegistry registry https://registry.npmjs.org/
    35 silly mapToRegistry uri https://registry.npmjs.org/browser-sync
    36 verbose addRemoteTarball https://registry.npmjs.org/browser-sync/-/browser-sync-2.8.2.tgz not in flight; adding
    37 verbose addRemoteTarball [ 'https://registry.npmjs.org/browser-sync/-/browser-sync-2.8.2.tgz',
    37 verbose addRemoteTarball   'd062ca0c88126337302a192236ee2c93d258f075' ]
    38 info retry fetch attempt 1 at 11:55:04
    39 info attempt registry request try #1 at 11:55:04
    40 http fetch GET https://registry.npmjs.org/browser-sync/-/browser-sync-2.8.2.tgz
    41 http fetch 200 https://registry.npmjs.org/browser-sync/-/browser-sync-2.8.2.tgz
    42 silly fetchAndShaCheck shasum d062ca0c88126337302a192236ee2c93d258f075
    43 verbose addTmpTarball /tmp/npm-19692-b03f3055/registry.npmjs.org/browser-sync/-/browser-sync-2.8.2.tgz not in flight; adding
    44 verbose addTmpTarball already have metadata; skipping unpack for browser-sync@2.8.2
    45 silly cache afterAdd browser-sync@2.8.2
    46 verbose afterAdd /home/sampablokuper/.npm/browser-sync/2.8.2/package/package.json not in flight; writing
    47 verbose afterAdd /home/sampablokuper/.npm/browser-sync/2.8.2/package/package.json written
    48 silly install resolved [ { name: 'browser-sync',
    48 silly install resolved     description: 'Live CSS Reload & Browser Syncing',
    48 silly install resolved     version: '2.8.2',
    48 silly install resolved     homepage: 'http://www.browsersync.io/',
    48 silly install resolved     author: { name: 'Shane Osbourne' },
    48 silly install resolved     repository:
    48 silly install resolved      { type: 'git',
    48 silly install resolved        url: 'git+https://github.com/browsersync/browser-sync.git' },
    48 silly install resolved     license: 'Apache-2.0',
    48 silly install resolved     bin: { 'browser-sync': 'bin/browser-sync.js' },
    48 silly install resolved     files: [ 'bin', 'index.js', 'lib' ],
    48 silly install resolved     engines: { node: '>= 0.8.0' },
    48 silly install resolved     scripts:
    48 silly install resolved      { env: 'node ./test/env.js',
    48 silly install resolved        test: 'npm run lint && npm run env && npm run unit',
    48 silly install resolved        lint: 'gulp lint',
    48 silly install resolved        pro: 'protractor test/protractor/config.single.js',
    48 silly install resolved        'pro-local': 'node test/protractor/setup.js',
    48 silly install resolved        unit: 'mocha --recursive test/specs --timeout 10000',
    48 silly install resolved        cover: 'npm run env && npm run cover-local && npm run coveralls',
    48 silly install resolved        'cover-local': 'istanbul cover _mocha -- --timeout 10000 --recursive ./test/specs',
    48 silly install resolved        coveralls: 'istanbul-coveralls',
    48 silly install resolved        'pre-release': 'npm test && npm run pro-local && npm run pro' },
    48 silly install resolved     dependencies:
    48 silly install resolved      { anymatch: '^1.3.0',
    48 silly install resolved        'async-each-series': '^0.1.1',
    48 silly install resolved        'browser-sync-client': '^2.2.1',
    48 silly install resolved        'browser-sync-ui': '^0.5.13',
    48 silly install resolved        chokidar: '^1.0.5',
    48 silly install resolved        connect: '^3.4.0',
    48 silly install resolved        'dev-ip': '^1.0.1',
    48 silly install resolved        'easy-extender': '^2.3.1',
    48 silly install resolved        'eazy-logger': '^2.1.2',
    48 silly install resolved        'emitter-steward': '^0.0.1',
    48 silly install resolved        foxy: '^11.1.1',
    48 silly install resolved        immutable: '^3.7.4',
    48 silly install resolved        localtunnel: '^1.7.0',
    48 silly install resolved        lodash: '^3.9.3',
    48 silly install resolved        longest: '^1.0.1',
    48 silly install resolved        meow: '^3.3.0',
    48 silly install resolved        opn: '^2.0.1',
    48 silly install resolved        'pad-left': '^1.0.2',
    48 silly install resolved        portscanner: '^1.0.0',
    48 silly install resolved        'query-string': '^2.4.0',
    48 silly install resolved        'resp-modifier': '^4.0.4',
    48 silly install resolved        'serve-index': '^1.7.0',
    48 silly install resolved        'serve-static': '^1.10.0',
    48 silly install resolved        'socket.io': '^1.3.6',
    48 silly install resolved        'ua-parser-js': '^0.7.9',
    48 silly install resolved        ucfirst: '0.0.1' },
    48 silly install resolved     devDependencies:
    48 silly install resolved      { 'browser-sync-spa': '^1.0.2',
    48 silly install resolved        'bs-snippet-injector': '^2.0.1',
    48 silly install resolved        chai: '^3.2.0',
    48 silly install resolved        chalk: '^1.1.0',
    48 silly install resolved        'graceful-fs': '^3.0.8',
    48 silly install resolved        gulp: '^3.9.0',
    48 silly install resolved        'gulp-contribs': '0.0.3',
    48 silly install resolved        'gulp-conventional-changelog': '^0.4.0',
    48 silly install resolved        'gulp-filter': '^2.0.2',
    48 silly install resolved        'gulp-jscs': '^1.6.0',
    48 silly install resolved        'gulp-jshint': '^1.11.2',
    48 silly install resolved        'gulp-ruby-sass': '^1.0.5',
    48 silly install resolved        'gulp-yuidoc': '^0.1.2',
    48 silly install resolved        istanbul: '^0.3.17',
    48 silly install resolved        'istanbul-coveralls': '^1.0.3',
    48 silly install resolved        mocha: '^2.2.5',
    48 silly install resolved        q: '^1.4.1',
    48 silly install resolved        request: '^2.60.0',
    48 silly install resolved        sinon: '^1.15.4',
    48 silly install resolved        slugify: '^0.1.1',
    48 silly install resolved        'socket.io-client': '^1.3.6',
    48 silly install resolved        supertest: '^1.0.1',
    48 silly install resolved        vinyl: '^0.5.0' },
    48 silly install resolved     keywords: [ 'browser sync', 'css', 'live reload', 'sync' ],
    48 silly install resolved     gitHead: 'd3b4601ff2b02fcff42396deceada43351d713d9',
    48 silly install resolved     bugs: { url: 'https://github.com/browsersync/browser-sync/issues' },
    48 silly install resolved     _id: 'browser-sync@2.8.2',
    48 silly install resolved     _shasum: 'd062ca0c88126337302a192236ee2c93d258f075',
    48 silly install resolved     _from: 'browser-sync@*',
    48 silly install resolved     _npmVersion: '2.11.3',
    48 silly install resolved     _nodeVersion: '0.12.2',
    48 silly install resolved     _npmUser: { name: 'shakyshane', email: 'shakyshane@gmail.com' },
    48 silly install resolved     dist:
    48 silly install resolved      { shasum: 'd062ca0c88126337302a192236ee2c93d258f075',
    48 silly install resolved        tarball: 'http://registry.npmjs.org/browser-sync/-/browser-sync-2.8.2.tgz' },
    48 silly install resolved     maintainers: [ [Object] ],
    48 silly install resolved     directories: {},
    48 silly install resolved     _resolved: 'https://registry.npmjs.org/browser-sync/-/browser-sync-2.8.2.tgz' } ]
    49 info install browser-sync@2.8.2 into /usr/lib
    50 info installOne browser-sync@2.8.2
    51 verbose installOne of browser-sync to /usr/lib not in flight; installing
    52 verbose makeDirectory /home/sampablokuper/.npm/_locks creation not in flight; initializing
    53 silly makeDirectory /home/sampablokuper/.npm/_locks uid: 1000 gid: 1000
    54 verbose lock using /home/sampablokuper/.npm/_locks/browser-sync-69d4a3d208cd60c3.lock for /usr/lib/node_modules/browser-sync
    55 silly install write writing browser-sync 2.8.2 to /usr/lib/node_modules/browser-sync
    56 verbose unbuild lib/node_modules/browser-sync
    57 silly gentlyRm /usr/lib/node_modules/browser-sync is being purged from base /usr
    58 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/browser-sync
    59 verbose tar unpack /home/sampablokuper/.npm/browser-sync/2.8.2/package.tgz
    60 verbose tar unpacking to /usr/lib/node_modules/browser-sync
    61 silly gentlyRm /usr/lib/node_modules/browser-sync is being purged
    62 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/browser-sync
    63 silly gunzTarPerm modes [ '755', '644' ]
    64 error tar.unpack untar error /home/sampablokuper/.npm/browser-sync/2.8.2/package.tgz
    65 verbose unlock done using /home/sampablokuper/.npm/_locks/browser-sync-69d4a3d208cd60c3.lock for /usr/lib/node_modules/browser-sync
    66 verbose fstream_path /usr/lib/node_modules/browser-sync
    67 verbose fstream_type Directory
    68 verbose fstream_class DirWriter
    69 verbose stack Error: EACCES, mkdir '/usr/lib/node_modules/browser-sync'
    70 verbose fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25
    70 verbose fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53
    70 verbose fstream_stack Object.oncomplete (fs.js:107:15)
    71 verbose cwd /home/sampablokuper
    72 error Linux 3.16.0-4-686-pae
    73 error argv "node" "/usr/bin/npm" "install" "-g" "browser-sync"
    74 error node v0.10.29
    75 error npm  v2.14.0
    76 error path /usr/lib/node_modules/browser-sync
    77 error code EACCES
    78 error errno 3
    79 error Error: EACCES, mkdir '/usr/lib/node_modules/browser-sync'
    79 error  { [Error: EACCES, mkdir '/usr/lib/node_modules/browser-sync']
    79 error   errno: 3,
    79 error   code: 'EACCES',
    79 error   path: '/usr/lib/node_modules/browser-sync',
    79 error   fstream_type: 'Directory',
    79 error   fstream_path: '/usr/lib/node_modules/browser-sync',
    79 error   fstream_class: 'DirWriter',
    79 error   fstream_stack:
    79 error    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
    79 error      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
    79 error      'Object.oncomplete (fs.js:107:15)' ] }
    80 error Please try running this command again as root/Administrator.
    81 verbose exit [ 3, true ]
    82 verbose unbuild lib/node_modules/browser-sync
    83 silly gentlyRm /usr/lib/node_modules/browser-sync is being purged from base /usr
    84 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/browser-sync

**Comment by shinnn** [comment]
That's a npm issue.

**Comment by sampablokuper** [comment]
> That's a npm issue.

Not when your *documentation*'s steps don't match what the user experiences when (s)he follows them. Then it's a documentation issue.

Incidentally, I finally managed to get BrowserSync working by adding the following steps to my "from scratch" steps above, so you may wish to add these (or something like them) to your installation instructions:

    $ echo prefix=${HOME}/.npm >> ~/.npmrc
    $ echo 'export PATH="$HOME/.npm/bin:$PATH"' >> ~/.bashrc
    $ source ~/.bashrc
    $ npm install -g browser-sync

**Comment by shinnn** [comment]
Should be documented [here](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions) if it's a really better instructions. https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager/_edit

**Comment by sampablokuper** [comment]
> Should be documented [here](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions) if it's a really better instructions. https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager/_edit

Er, no. That Wiki page is about installing Node.js.

As I said earlier, `# apt-get install nodejs` worked fine. So the first step of the BrowserSync documentation's installation instructions, which is about installing Node.js, wasn't problematic.

**Comment by shinnn** [comment]
Like the official installer and Homebrew package, Node installer or a package also installs npm, generally. If `apt-get install nodejs` doesn't install `npm` correctly, it should be notified on that Wiki.

**Comment by sampablokuper** [comment]
Some do; some don't. Debian's doesn't. BrowserSync's documentation shouldn't assume one way or the other.

If BrowserSync has npm as a prerequisite, **say so** explicitly in the BrowserSync docs. (Likewise if BrowserSync requires a particular version of npm, or requires it to be configured in some specific way.)

It is standard practice (and good practice!) for a package's installation instructions to clearly state the installation prerequisites, but your comments above make it seem as though you are trying to avoid this (and indeed to avoid improving the BrowserSync installation instructions at all).Why are you so keen to avoid this?

**Comment by shakyShane** [comment]
@sampablokuper - we understand your frustration. 

Can you install other packages from npm globally without issue?

**Comment by sampablokuper** [comment]
@shakyShane Thanks for your understanding.

I'm afraid there are no other npm packages I need/want to install at the moment, so it isn't easy for me to test this, sorry. I only installed npm in order to be able to try BrowserSync (which I like, btw, apart from the installation rigmarole!).

Given that Debian and Debian-derived GNU/Linux distros (e.g. Ubuntu, Mint) have consistently been among the most popular GNU/Linux distros over the [last 12 months](http://distrowatch.com/dwres.php?resource=popularity) and beyond, it's probably worthwhile ensuring that BrowserSync's installation instructions work smoothly on at least Debian Stable. At the moment, they don't, as you can see above.

Thanks again.
