### ISSUE TITLE
/docs/options/ - default rendering issue

### ISSUE THREAD

**Issue by jhuskisson** [BrowserSync/browsersync.github.io#4]
http://www.browsersync.io/docs/options/#snippetOptions

"rule.match - Default: /&lt;body&#91;^&gt;&#93;*&gt;/i" is displaying as HTML entities and not rendering the tag output properly. 

Note: Github just renders the text in this issue, which isn't hugely helpful so i've attached an image. 
![screen shot 2015-02-10 at 22 41 05](https://cloud.githubusercontent.com/assets/106556/6138074/eb28d84c-b175-11e4-914d-bed444e8d56d.png)

**Comment by shakyShane** [comment]
![aw yeah](http://cl.ly/image/1Z3g291P3D3t/Screen%20Shot%202015-02-13%20at%2011.40.29.png)
